/*
 * The MIT License
 *
 * Copyright 2020 Paolo.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package accord;

import java.util.ArrayList;
import simulator.SimulationConstants;

/**
 *
 * @author Paolo
 */
public class AddCustomCar extends javax.swing.JFrame implements SimulationConstants{

    /**
     * Creates new form AddCustomCar
     */
    public AddCustomCar() {
        initComponents();
    }
    public AddCustomCar(ACCORD_UI ui) {
        initComponents();
        accord_ui = ui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtf_xLoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtf_yLoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtf_orient = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_route = new javax.swing.JComboBox<>();
        btn_addRoute = new javax.swing.JButton();
        btn_clearRoute = new javax.swing.JButton();
        btn_done = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_carDetails = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtf_throttle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtf_carID = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("X (mm)");

        jLabel2.setText("Y (mm)");

        jLabel3.setText("Orientation (deg)");

        jLabel5.setText("Route");

        cmb_route.setModel(new javax.swing.DefaultComboBoxModel<>(MANEUVER_STRINGS));

        btn_addRoute.setText("Add");
        btn_addRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addRouteActionPerformed(evt);
            }
        });

        btn_clearRoute.setText("Clear");
        btn_clearRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearRouteActionPerformed(evt);
            }
        });

        btn_done.setText("ADD CAR");
        btn_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doneActionPerformed(evt);
            }
        });

        txta_carDetails.setColumns(20);
        txta_carDetails.setRows(5);
        jScrollPane1.setViewportView(txta_carDetails);

        jLabel6.setText("Enter Details of New Simulated Car.");

        jLabel7.setText("Throttle (0-100)");

        jLabel8.setText("Current Car Details:");

        jLabel9.setText("Car ID (0xXXXX)");

        txtf_carID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_carIDActionPerformed(evt);
            }
        });

        btn_refresh.setText("refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(btn_done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(80, 80, 80)
                        .addComponent(cmb_route, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_addRoute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clearRoute))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtf_throttle, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                    .addComponent(txtf_orient)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtf_yLoc)
                                    .addComponent(txtf_carID)
                                    .addComponent(txtf_xLoc))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtf_carID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtf_xLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtf_yLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtf_orient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtf_throttle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_route, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addRoute)
                    .addComponent(btn_clearRoute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btn_refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_done, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private ACCORD_UI accord_ui;
    public void setACCORD_UI(ACCORD_UI ui){
        accord_ui = ui;
    }
    private final String[] HEADING_STRINGS = {"EAST", "NORTH", "WEST", "SOUTH"};
    private final String[] MANEUVER_STRINGS = {"Left turn", "Straight", "Right turn"};
    private Car newCustomCar = null;
    boolean done = false;
    private void btn_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doneActionPerformed
        if(!allInputsFilled()){
            txta_carDetails.setText("Please fill in all the details...");
            return;
        }
        int carID = Integer.parseInt(txtf_carID.getText(), 16);
        Car car = new SimulatedCar(carID);

        int x = Integer.parseInt(txtf_xLoc.getText());
        int y = Integer.parseInt(txtf_yLoc.getText());
        int throttle = Integer.parseInt(txtf_throttle.getText());
        double orient = Double.parseDouble(txtf_orient.getText());

        car.setAttributesManual(carID, x, y, orient, Car.DEFAULT_XDim, Car.DEFAULT_YDim, 0);
        car.adjustThrottle(throttle);
        for(int routeTurn : routeList){
            car.addRouteDirection(routeTurn);
        }
        newCustomCar = car;
        done = true;
        this.setVisible(false);
        accord_ui.updateCustomCarList(this);
    }//GEN-LAST:event_btn_doneActionPerformed
    private boolean allInputsFilled(){
        return !(txtf_carID.getText().isEmpty()
                || txtf_xLoc.getText().isEmpty()
                || txtf_yLoc.getText().isEmpty()
                || txtf_orient.getText().isEmpty()
                || txtf_throttle.getText().isEmpty());
    }
    public Car getNewCustomCar(){
        return newCustomCar;
    }
    
    private int headingStringToInt(String heading){
        switch(heading){
            case "EAST":
                return EAST;
            case "NORTH":
                return NORTH;
            case "WEST":
                return WEST;
            case "SOUTH":
                return SOUTH;
            default:
                return 0;
        }
    }
    private int maneuverStringToInt(String maneuver){
        switch(maneuver){
            case "Left turn":
                return LEFT_TURN;
            case "Straight":
                return STRAIGHT;
            case "Right turn":
                return RIGHT_TURN;
            default:
                return 0;
        }
    }
    
    private void txtf_carIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_carIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_carIDActionPerformed
    
    private ArrayList<Integer> routeList = new ArrayList<>();
    private void btn_addRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addRouteActionPerformed
        int routeTurn = maneuverStringToInt(MANEUVER_STRINGS[cmb_route.getSelectedIndex()]);
        routeList.add(routeTurn);
    }//GEN-LAST:event_btn_addRouteActionPerformed

    private void btn_clearRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearRouteActionPerformed
        routeList.clear();
    }//GEN-LAST:event_btn_clearRouteActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        if(!allInputsFilled()){
            txta_carDetails.setText("Please fill in all the details...");
            return;
        }
        int carID = Integer.parseInt(txtf_carID.getText(), 16);
        Car car = new SimulatedCar(carID);

        int x = Integer.parseInt(txtf_xLoc.getText());
        int y = Integer.parseInt(txtf_yLoc.getText());
        int throttle = Integer.parseInt(txtf_throttle.getText());
        double orient = Double.parseDouble(txtf_orient.getText());

        car.setAttributesManual(carID, x, y, orient, Car.DEFAULT_XDim, Car.DEFAULT_YDim, 0);
        car.adjustThrottle(throttle);
        for(int routeTurn : routeList){
            car.addRouteDirection(routeTurn);
        }
        newCustomCar = car;
        
        if(newCustomCar == null)
            return;
        
        String deets = "";
        deets += "Car ID: 0x" + Integer.toHexString(newCustomCar.getID());
        deets += "\nX: " + newCustomCar.getXLocation();
        deets += "\nY: " + newCustomCar.getXLocation();
        deets += "\nOrientation: " + newCustomCar.getOrientation();
        deets += "\nThrottle: " + newCustomCar.getThrottlePower();
        
        deets += "\nRoute List:";
        for(int route : routeList)
            deets += "\n" + route;
        
        txta_carDetails.setText(deets);
    }//GEN-LAST:event_btn_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addRoute;
    private javax.swing.JButton btn_clearRoute;
    private javax.swing.JButton btn_done;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox<String> cmb_route;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txta_carDetails;
    private javax.swing.JTextField txtf_carID;
    private javax.swing.JTextField txtf_orient;
    private javax.swing.JTextField txtf_throttle;
    private javax.swing.JTextField txtf_xLoc;
    private javax.swing.JTextField txtf_yLoc;
    // End of variables declaration//GEN-END:variables
}
